clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      # 【关键1】禁用部分克隆 (partial clone)，改为浅克隆 (depth 1)
      # 部分克隆在国内网络环境下非常容易断流
      partial: false
      depth: 1
      # 增加重试次数
      tags: true
    # 按需注入代理
    environment:
      - https_proxy=http://172.24.173.76:7899
      - http_proxy=http://172.24.173.76:7899
      # 记得把内网IP加入 no_proxy，防止推镜像时走代理
      - no_proxy=localhost,127.0.0.1,10.42.0.0/16,10.43.0.0/16,172.24.173.77
steps:
  build-and-push:
    # 【关键修改】使用刚才搬运的 plugins/docker 镜像
    image: 172.24.173.77:30500/standard-docker:latest

    # 特权模式依然是必须的
    privileged: true

    # 注入代理，让它能拉取 FROM 基础镜像
    environment:
      - https_proxy=http://172.24.173.76:7899
      - http_proxy=http://172.24.173.76:7899
      - no_proxy=localhost,127.0.0.1,172.24.173.77,10.42.0.0/16,10.43.0.0/16

    settings:
      # 这里的配置和 woodpecker 插件完全通用
      registry: http://172.24.173.77:30500
      repo: 172.24.173.77:30500/ai-image
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:7}
      insecure: true
      # 这个插件很简单，不需要 driver_opts
      # 如果需要构建参数：
      build_args:
        - http_proxy=http://172.24.173.76:7899
        - https_proxy=http://172.24.173.76:7899
      # Dockerfile 路径 (如果就在根目录，这行可以删掉)
      # dockerfile: Dockerfile

      # 认证信息
      # 如果你的私有仓库没有设置密码，这两行可以直接删掉
      # 如果有密码，请去 Woodpecker 网页端 Secrets 配置
      # username:
      #   from_secret: docker_username
      # password:
      #   from_secret: docker_password