clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      # 【关键1】禁用部分克隆 (partial clone)，改为浅克隆 (depth 1)
      # 部分克隆在国内网络环境下非常容易断流
      partial: false
      depth: 1
      # 增加重试次数
      tags: true
    # 按需注入代理
    environment:
      - https_proxy=http://172.24.173.76:7899
      - http_proxy=http://172.24.173.76:7899
      # 记得把内网IP加入 no_proxy，防止推镜像时走代理
      - no_proxy=localhost,127.0.0.1,10.42.0.0/16,10.43.0.0/16,172.24.173.77
steps:
  build-and-push:
    image: 172.24.173.77:30500/woodpecker-plugin-docker-buildx:latest
    privileged: true
    settings:
      registry: http://172.24.173.77:30500
      repo: 172.24.173.77:30500/ai-image
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:7}
      insecure: true
      driver_opts:
        - image=172.24.173.77:30500/moby-buildkit:buildx-stable-1
        # 告诉 BuildKit 进程走代理
        - env.http_proxy=http://172.24.173.76:7899
        - env.https_proxy=http://172.24.173.76:7899
        - env.no_proxy=localhost,127.0.0.1,172.24.173.77,10.42.0.0/16

      # 【修改3】配置构建过程参数 (执行 RUN 命令用)
      build_args:
        - http_proxy=http://172.24.173.76:7899
        - https_proxy=http://172.24.173.76:7899
      # Dockerfile 路径 (如果就在根目录，这行可以删掉)
      # dockerfile: Dockerfile

      # 认证信息
      # 如果你的私有仓库没有设置密码，这两行可以直接删掉
      # 如果有密码，请去 Woodpecker 网页端 Secrets 配置
      # username:
      #   from_secret: docker_username
      # password:
      #   from_secret: docker_password